MilliTakim/Controllers/BiletController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MilliTakim.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MilliTakim.Controllers
{
    [Authorize]
    public class BiletController : Controller
    {
        private readonly WebContext _context;
        public BiletController(WebContext context)
        {
            _context = context;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var webContext = await _context.bilet.ToListAsync();
            ViewData["bilet"] = new Bilet();
            return View(webContext);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> BiletEkle(Bilet bilet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bilet);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> BiletSil(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _bilet = await _context.bilet.FindAsync(id);
            if (_bilet == null)
            {
                return View("Bulunamadi");
            }
            _context.bilet.Remove(_bilet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> BiletDuzenle(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _bilet = await _context.bilet.FindAsync(id);
            if (_bilet == null)
            {
                return View("Bulunamadi");
            }
            return View(_bilet);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> BiletDuzenle(Bilet bilet, int id)
        {
            if (id != bilet.biletId)
            {
                return View("Bulunamadi");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bilet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiletExists(bilet.biletId))
                    {
                        return View("Bulunamadi");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> BiletSatinAl(int?id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _bilet = await _context.bilet.FindAsync(id);
            if (_bilet == null)
            {
                return View("Bulunamadi");
            }
            return View(_bilet);
        }

        [HttpPost]
        public async Task<IActionResult> BiletSatinAl(Bilet bilet, int id)
        {
            if (id != bilet.biletId || bilet.biletAdet == 0)
            {
                return View("Bulunamadi");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    bilet.biletAdet = bilet.biletAdet-1;
                    _context.Update(bilet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BiletExists(bilet.biletId))
                    {
                        return View("Bulunamadi");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return View("SatinAlmaBasarili");
        }


        private bool BiletExists(int id)
        {
            return _context.bilet.Any(e => e.biletId == id);
        }
    }
}

MilliTakim/Controllers/FutbolcuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MilliTakim.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace MilliTakim.Controllers
{
    public class FutbolcuController : Controller
    {
        private readonly WebContext _context;
        public FutbolcuController(WebContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var webContext = await _context.futbolcu.ToListAsync();
            ViewData["futbolcu"] = new Futbolcu();
            return View(webContext);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> FutbolcuEkle(Futbolcu futbolcu)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        futbolcu.ProfilePicture = dataStream.ToArray();
                    }
                }
                _context.Add(futbolcu);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> FutbolcuSil(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _futbolcu = await _context.futbolcu.FindAsync(id);
            if (_futbolcu == null)
            {
                return View("Bulunamadi");
            }
            _context.futbolcu.Remove(_futbolcu);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> FutbolcuDuzenle(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _futbolcu = await _context.futbolcu.FindAsync(id);
            if (_futbolcu == null)
            {
                return View("Bulunamadi");
            }
            return View(_futbolcu);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> FutbolcuDuzenle(Futbolcu futbolcu,int id)
        {
            if (id != futbolcu.playerId)
            {
                return View("Bulunamadi");
            }
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        futbolcu.ProfilePicture = dataStream.ToArray();
                    }
                }
                try
                {
                    _context.Update(futbolcu);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FutbolcuExists(futbolcu.playerId))
                    {
                        return View("Bulunamadi");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

        private bool FutbolcuExists(int id)
        {
            return _context.futbolcu.Any(e => e.playerId == id);
        }
    }
}

MilliTakim/Controllers/MagazaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MilliTakim.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MilliTakim.Controllers
{
    public class MagazaController : Controller
    {
        private readonly WebContext _context;
        public MagazaController(WebContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var webContext = await _context.magaza.ToListAsync();
            ViewData["magaza"] = new Magaza();
            return View(webContext);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> MagazaUrunEkle(Magaza magaza)
        {
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        magaza.ProfilePicture = dataStream.ToArray();
                    }
                }
                _context.Add(magaza);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public IActionResult MagazaSatinAl(int fiyat)
        {
            ViewBag.total = fiyat;
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult MagazaSatinAl()
        {
            return View("SatinAlmaBasarili");
        }


        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> MagazaDuzenle(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _magaza = await _context.magaza.FindAsync(id);
            if (_magaza == null)
            {
                return View("Bulunamadi");
            }
            return View(_magaza);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> MagazaDuzenle(Magaza magaza, int id)
        {
            if (id != magaza.urunId)
            {
                return View("Bulunamadi");
            }
            if (ModelState.IsValid)
            {
                if (Request.Form.Files.Count > 0)
                {
                    IFormFile file = Request.Form.Files.FirstOrDefault();
                    using (var dataStream = new MemoryStream())
                    {
                        await file.CopyToAsync(dataStream);
                        magaza.ProfilePicture = dataStream.ToArray();
                    }
                }
                try
                {
                    _context.Update(magaza);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MagazaExists(magaza.urunId))
                    {
                        return View("Bulunamadi");
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> MagazaSil(int? id)
        {
            if (id == null)
            {
                return View("Bulunamadi");
            }
            var _magaza = await _context.magaza.FindAsync(id);
            if (_magaza == null)
            {
                return View("Bulunamadi");
            }
            _context.magaza.Remove(_magaza);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        private bool MagazaExists(int id)
        {
            return _context.magaza.Any(e => e.urunId == id);
        }

    }
}

MilliTakim/Views/Shared/Bulunamadi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<h5>@localizer["Aradığınız Sayfa Bulunamadı"] !</h5>

MilliTakim/Views/Shared/SatinAlmaBasarili.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
<h5>@localizer["Satın Alma Başarıyla Tamamlandı"] !</h5>

MilliTakim/Views/Shared/_Culture.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer
@inject Microsoft.Extensions.Options.IOptions<Microsoft.AspNetCore.Builder.RequestLocalizationOptions> locOptions
@{ 
    var culture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    var cultureList = locOptions.Value.SupportedUICultures.Select(x => new SelectListItem { Value = x.Name, Text = localizer.GetString(x.Name) }).ToList();
    var returnUrl = string.IsNullOrWhiteSpace(Context.Request.Path) ? "~/" : $"~{Context.Request.Path.Value}{Context.Request.QueryString}";
}
    <form asp-action="CultureManagement" asp-controller="Home" method="post" asp-route-returnUrl="@returnUrl">
        <select name="culture" asp-for="@culture.RequestCulture.UICulture.Name" asp-items="cultureList" onchange="this.form.submit();">
        </select>
    </form>

MilliTakim/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer localizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MilliTakim</title>

    <script src="~/lib/bootstrap/dist/js/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/sosyal_medya.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@localizer["Anasayfa"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Tarihce">@localizer["Tarihçe"]</a>
</li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Futbolcu" asp-action="Index">@localizer["Futbolcularımız"]</a>
</li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Bilet" asp-action="Index">@localizer["Bilet Al"]</a>
</li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Magaza" asp-action="Index">@localizer["Mağaza"]</a>
</li>
                <li class="nav-item">
                    <partial name="_Culture" />
                </li>
            </ul>
            <partial name="_LoginPartial.cshtml" />
        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer">
        <div class="ml-auto asd">
            <div class="template-demo"><button onclick="window.location.href = 'https://www.facebook.com'" type="button" class="btn btn-social-icon btn-facebook"><i class="fa fa-facebook"></i></button><button onclick="window.location.href = 'https://www.youtube.com'" type="button" class="btn btn-social-icon btn-youtube"><i class="fa fa-youtube"></i></button><button onclick="window.location.href = 'https://www.twitter.com'" type="button" class="btn btn-social-icon btn-twitter"><i class="fa fa-twitter"></i></button><button onclick="window.location.href = 'https://www.instagram.com'" type="button" class="btn btn-social-icon btn-instagram"><i class="fa fa-instagram"></i></button></div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>